#!/usr/bin/env python3
"""
SessionEnd hook — writes a stub session file to ~/Knowledge/sessions/

Detects which repos changed in the last 3 hours, pulls recent commits,
and writes a dated markdown file. Not AI-summarized — factual record only.
Run /dream to enhance stubs into narratives.

Claude Code pipes JSON to stdin: {"session_id": "...", "transcript_path": "..."}
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

# ── config ──────────────────────────────────────────────────────────────────
SESSIONS_DIR = Path.home() / "Knowledge" / "sessions"
MEMORY_MD = Path.home() / "Knowledge" / "claude-memory" / "MEMORY.md"
LOOKBACK_HOURS = 3

WATCHED_REPOS = [
    ("brokerbridge-retail", Path.home() / "Projects" / "brokerbridge-retail"),
    ("brokerbridge-enterprise", Path.home() / "Projects" / "MCP-Servers" / "brokerbridge"),
    ("llm-cortex", Path.home() / "Projects" / "llm-cortex"),
    ("clawd", Path.home() / "clawd"),
    ("openclaw", Path.home() / "Projects" / "openclaw"),
    ("crucible", Path.home() / "Projects" / "crucible"),
    ("matrix-lstm", Path.home() / "Projects" / "matrix-lstm"),
    ("ymi-signals-app", Path.home() / "Projects" / "ymi-signals-app"),
    ("ymi-website", Path.home() / "Projects" / "ymi-website"),
    ("moltytrades", Path.home() / "Projects" / "moltytrades"),
    ("trading-systems", Path.home() / "Projects" / "Trading-Systems"),
    ("demand-index-oscillator", Path.home() / "demand-index-oscillator"),
    ("newsletter-executor", Path.home() / "Projects" / "newsletter-executor"),
    ("kpl-image-recognition", Path.home() / "Projects" / "KPL-image-recognition"),
    ("brokerbridge-retail-marketing", Path.home() / "Projects" / "brokerbridge-retail" / "marketing"),
]


def run(cmd, cwd=None):
    try:
        r = subprocess.run(
            cmd, cwd=cwd, capture_output=True, text=True, timeout=5
        )
        return r.stdout.strip()
    except Exception:
        return ""


def recent_commits(repo_path, hours=LOOKBACK_HOURS, max_commits=6):
    since = f"--since={hours} hours ago"
    out = run(
        ["git", "log", "--oneline", since, f"--max-count={max_commits}"],
        cwd=repo_path,
    )
    return [line for line in out.splitlines() if line.strip()]


def repo_has_changes(repo_path, hours=LOOKBACK_HOURS):
    commits = recent_commits(repo_path, hours)
    if commits:
        return True
    # Also check for uncommitted changes touched recently
    status = run(["git", "status", "--short"], cwd=repo_path)
    return bool(status.strip())


def slugify(text):
    return text.lower().replace(" ", "-").replace("/", "-")[:40]


def main():
    # Read stdin
    try:
        raw = sys.stdin.read()
        data = json.loads(raw) if raw.strip() else {}
    except Exception:
        data = {}

    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M CDT")

    SESSIONS_DIR.mkdir(parents=True, exist_ok=True)

    # Find repos with recent activity
    active_repos = []
    for label, path in WATCHED_REPOS:
        if not path.exists():
            continue
        if not (path / ".git").exists() and not (path.parent / ".git").exists():
            continue
        commits = recent_commits(path)
        if commits:
            active_repos.append((label, path, commits))

    if not active_repos:
        # No git activity — skip writing a stub
        sys.exit(0)

    # Build slug from most-active repo
    primary_label = active_repos[0][0]
    slug = slugify(primary_label)
    filename = f"{date_str}-{slug}.md"
    out_path = SESSIONS_DIR / filename

    # Don't overwrite a file that already has narrative content (> 20 lines)
    if out_path.exists():
        existing_lines = out_path.read_text().splitlines()
        if len(existing_lines) > 20:
            # Append a compact addendum instead
            addendum = f"\n## Addendum — {time_str}\n\n"
            for label, path, commits in active_repos:
                addendum += f"**{label}:**\n"
                for c in commits[:3]:
                    addendum += f"- `{c}`\n"
            with open(out_path, "a") as f:
                f.write(addendum)
            sys.exit(0)

    # Write stub
    lines = [
        f"# Session: {primary_label} — {date_str}",
        "",
        f"**Auto-generated by SessionEnd hook at {time_str}**  ",
        f"Run `/dream` to enhance into a narrative.",
        "",
        "## Repos with activity",
        "",
    ]

    for label, path, commits in active_repos:
        lines.append(f"### {label}")
        lines.append("")
        for c in commits:
            lines.append(f"- `{c}`")
        lines.append("")

    lines += [
        "## What happened",
        "",
        "_Not yet written. Run `/dream` or ask Claude to fill this in._",
        "",
    ]

    out_path.write_text("\n".join(lines))

    # Update MEMORY.md — append pointer under Sessions block if not already there
    if MEMORY_MD.exists():
        content = MEMORY_MD.read_text()
        session_pointer = f"- [{date_str} {primary_label}](../sessions/{filename})"
        if filename not in content:
            # Insert after the Sessions header line
            sessions_header = "### Sessions (recent)"
            if sessions_header in content:
                content = content.replace(
                    sessions_header,
                    f"{sessions_header}\n{session_pointer}",
                )
                MEMORY_MD.write_text(content)

    sys.exit(0)


if __name__ == "__main__":
    main()
