#!/usr/bin/env python3
"""
Context Registry Sync — Generate provider-specific configs from YAML source of truth.

Usage:
    python3 sync_context.py                    # Preview all adapters (dry run)
    python3 sync_context.py --preview claude   # Preview Claude Code output
    python3 sync_context.py --apply claude     # Write Claude Code config
    python3 sync_context.py --apply all        # Write all provider configs
    python3 sync_context.py --diff claude      # Show diff vs current config
    python3 sync_context.py --check            # Validate YAML files (no output)

Adapters read from context/*.yaml and produce provider-native config sections.
Nothing is written without --apply. Credentials are NEVER included in output.
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

CONTEXT_DIR = Path(__file__).resolve().parent.parent / "context"
HOME = Path.home()

ADAPTER_TARGETS = {
    "claude": HOME / ".claude" / "CLAUDE_CONTEXT.md",  # new file, not CLAUDE.md
    "cursor": None,  # project-level, handled per-project
    "codex": HOME / ".codex" / "CONTEXT.md",
    "cami": HOME / "Documents" / "shared-facts.md",
    "generic": HOME / "Projects" / "llm-cortex" / "context" / "shared-context.json",
}


# ---------------------------------------------------------------------------
# YAML Loading
# ---------------------------------------------------------------------------

def load_context() -> dict[str, Any]:
    """Load all YAML context files into a single dict."""
    context = {}
    for yaml_file in sorted(CONTEXT_DIR.glob("*.yaml")):
        key = yaml_file.stem
        with open(yaml_file) as f:
            data = yaml.safe_load(f)
        if data:
            context[key] = data
    return context


def validate_context(context: dict) -> list[str]:
    """Check for REVIEW markers and missing required fields."""
    issues = []
    for filename, data in context.items():
        yaml_str = yaml.dump(data)
        review_count = yaml_str.count("REVIEW")
        if review_count > 0:
            issues.append(f"{filename}.yaml: {review_count} REVIEW marker(s) — needs Cameron's input")
    if "infrastructure" not in context:
        issues.append("infrastructure.yaml missing — critical for Claude Code")
    if "projects" not in context:
        issues.append("projects.yaml missing — critical for all providers")
    return issues


# ---------------------------------------------------------------------------
# Adapters
# ---------------------------------------------------------------------------

def _strip_credentials(infra: dict) -> dict:
    """Remove any credential fields from infrastructure data."""
    import copy
    safe = copy.deepcopy(infra)
    for host in safe.get("hosts", {}).values():
        # Keep SSH command but strip passwords
        for svc in host.get("services", {}).values():
            if isinstance(svc, dict):
                for key in ("password", "secret", "api_key", "token"):
                    svc.pop(key, None)
                for user_data in svc.get("users", {}).values():
                    if isinstance(user_data, dict):
                        user_data.pop("password", None)
    return safe


def adapt_claude(context: dict) -> str:
    """Generate Claude Code context section from registry."""
    lines = [
        "# Personal Context (auto-generated by llm-cortex sync_context.py)",
        f"# Source: ~/Projects/llm-cortex/context/*.yaml",
        f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"# To update: edit the YAML files, then run sync_context.py --apply claude",
        "",
    ]

    # Identity
    identity = context.get("identity", {})
    person = identity.get("person", {})
    if person:
        lines.append("## Identity")
        lines.append(f"- **Name:** {person.get('name', 'Unknown')}")
        lines.append(f"- **Timezone:** {person.get('timezone', 'Unknown')}")
        lines.append(f"- **Role:** {person.get('role', 'Unknown')}")
        lines.append("")

    # Entities
    entities = identity.get("entities", {})
    if entities:
        lines.append("## Business Entities")
        for key, ent in entities.items():
            desc = ent.get("description", "")
            abbr = f" ({ent.get('abbreviation', '')})" if ent.get("abbreviation") else ""
            lines.append(f"- **{ent.get('name', key)}**{abbr}: {desc or '(no description)'}")
        lines.append("")

    # Team
    team = context.get("team", {})
    members = team.get("members", [])
    if members:
        lines.append("## Team")
        lines.append("| Name | Role |")
        lines.append("|------|------|")
        for m in members:
            lines.append(f"| {m.get('name', '?')} | {m.get('role', '(unset)')} |")
        lines.append("")

    # Projects
    projects = context.get("projects", {}).get("projects", {})
    if projects:
        lines.append("## Active Projects")
        lines.append("| Project | Path | Status |")
        lines.append("|---------|------|--------|")
        for key, proj in projects.items():
            path = proj.get("path", "?")
            status = proj.get("status", "?")
            lines.append(f"| {key} | `{path}` | {status} |")
        lines.append("")

    # Infrastructure (no credentials)
    infra = context.get("infrastructure", {})
    if infra:
        safe_infra = _strip_credentials(infra)
        hosts = safe_infra.get("hosts", {})
        lines.append("## Infrastructure (Tailscale)")
        lines.append("| Host | IP | Role |")
        lines.append("|------|-----|------|")
        for name, host in hosts.items():
            lines.append(f"| {name} | {host.get('ip', '?')} | {host.get('role', '?')} |")
        lines.append("")

    # Philosophy
    philosophy = identity.get("philosophy", [])
    if philosophy:
        lines.append("## Decision Philosophy")
        for p in philosophy:
            lines.append(f"- {p}")
        lines.append("")

    return "\n".join(lines)


def adapt_codex(context: dict) -> str:
    """Generate Codex context — focused on standards and project awareness."""
    lines = [
        "# Context (auto-generated by llm-cortex sync_context.py)",
        f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
    ]

    # Projects (names and paths only)
    projects = context.get("projects", {}).get("projects", {})
    if projects:
        lines.append("## Projects")
        for key, proj in projects.items():
            lines.append(f"- **{key}**: `{proj.get('path', '?')}` ({proj.get('status', '?')})")
        lines.append("")

    # Standards
    standards = context.get("standards", {})
    coding = standards.get("coding", {})
    if coding:
        lines.append("## Coding Standards")
        lines.append("- Virtual environment required")
        lines.append(f"- Data source: {coding.get('data_source', 'Storage VPS')}")
        lines.append("- DataGuard: fail fast on invalid data")
        lines.append("- Discovery before development")
        lines.append("- Modify, don't multiply (no _v2 files)")
        git = coding.get("git", {})
        if git:
            lines.append(f"- Commits: {git.get('commit_style', 'semantic')} style")
            lines.append(f"- Branches: {git.get('branch_style', 'feature/description')}")
        lines.append("")

    return "\n".join(lines)


def adapt_cursor(context: dict, project_key: str = "") -> str:
    """Generate Cursor .cursorrules — minimal, focused on code standards."""
    lines = [
        "# Auto-generated by llm-cortex sync_context.py",
        "",
    ]

    standards = context.get("standards", {})
    coding = standards.get("coding", {})
    if coding:
        lines.append("## Standards")
        lines.append("- Always activate venv first")
        lines.append(f"- Data source: {coding.get('data_source', 'Storage VPS')}")
        lines.append("- Fail fast on invalid/missing data")
        lines.append("- Search existing code before writing new")
        lines.append("- No _v2, _final, _enhanced file copies")
        lines.append("")

    # Project-specific context
    if project_key:
        projects = context.get("projects", {}).get("projects", {})
        proj = projects.get(project_key, {})
        if proj:
            lines.append(f"## Project: {project_key}")
            lines.append(f"- Path: `{proj.get('path', '?')}`")
            lines.append(f"- Language: {proj.get('language', '?')}")
            lines.append(f"- Status: {proj.get('status', '?')}")
            if proj.get("description"):
                lines.append(f"- {proj['description']}")
            lines.append("")

    return "\n".join(lines)


def adapt_generic(context: dict) -> str:
    """Generate shared-context.json — machine-readable, for any consumer."""
    import json

    output = {
        "generated_at": datetime.now().isoformat(),
        "source": "llm-cortex/context/*.yaml",
        "identity": context.get("identity", {}).get("person", {}),
        "entities": context.get("identity", {}).get("entities", {}),
        "team": context.get("team", {}).get("members", []),
        "projects": {
            k: {"path": v.get("path"), "status": v.get("status"), "language": v.get("language")}
            for k, v in context.get("projects", {}).get("projects", {}).items()
        },
        "infrastructure": {
            name: {"ip": h.get("ip"), "role": h.get("role")}
            for name, h in context.get("infrastructure", {}).get("hosts", {}).items()
        },
    }
    return json.dumps(output, indent=2)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

ADAPTERS = {
    "claude": adapt_claude,
    "codex": adapt_codex,
    "cursor": adapt_cursor,
    "generic": adapt_generic,
}


def main():
    parser = argparse.ArgumentParser(description="Sync personal context to LLM provider configs")
    parser.add_argument("--preview", metavar="PROVIDER", help="Preview output for a provider")
    parser.add_argument("--apply", metavar="PROVIDER", help="Write output to provider config (or 'all')")
    parser.add_argument("--diff", metavar="PROVIDER", help="Show diff between current and generated")
    parser.add_argument("--check", action="store_true", help="Validate YAML files only")
    args = parser.parse_args()

    context = load_context()

    if args.check:
        issues = validate_context(context)
        if issues:
            print("Validation issues:")
            for issue in issues:
                print(f"  - {issue}")
            sys.exit(1 if any("missing" in i.lower() for i in issues) else 0)
        else:
            print("All context files valid.")
            sys.exit(0)

    if args.preview:
        provider = args.preview.lower()
        if provider not in ADAPTERS:
            print(f"Unknown provider: {provider}. Available: {', '.join(ADAPTERS)}")
            sys.exit(1)
        print(ADAPTERS[provider](context))
        return

    if args.diff:
        provider = args.diff.lower()
        if provider not in ADAPTERS:
            print(f"Unknown provider: {provider}")
            sys.exit(1)
        generated = ADAPTERS[provider](context)
        target = ADAPTER_TARGETS.get(provider)
        if target and target.exists():
            current = target.read_text()
            if current == generated:
                print(f"{provider}: No changes needed")
            else:
                print(f"{provider}: Changes detected")
                # Simple line-by-line diff
                import difflib
                diff = difflib.unified_diff(
                    current.splitlines(keepends=True),
                    generated.splitlines(keepends=True),
                    fromfile=str(target),
                    tofile="(generated)",
                )
                print("".join(diff))
        else:
            print(f"{provider}: Target file does not exist yet ({target})")
            print(generated)
        return

    if args.apply:
        provider = args.apply.lower()
        providers = list(ADAPTERS.keys()) if provider == "all" else [provider]
        for p in providers:
            if p not in ADAPTERS:
                print(f"Skipping unknown provider: {p}")
                continue
            generated = ADAPTERS[p](context)
            target = ADAPTER_TARGETS.get(p)
            if target:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(generated)
                print(f"[OK] {p}: wrote {target}")
            else:
                print(f"[SKIP] {p}: no target path (project-level adapter)")
        return

    # Default: preview all + validation
    issues = validate_context(context)
    if issues:
        print("=== Validation ===")
        for issue in issues:
            print(f"  - {issue}")
        print()

    for name, adapter in ADAPTERS.items():
        print(f"=== {name} adapter ===")
        target = ADAPTER_TARGETS.get(name, "(no target)")
        print(f"Target: {target}")
        print()
        print(adapter(context))
        print()


if __name__ == "__main__":
    main()
